mono = createFont("monospace")
verdana = createFont('verdana')
georgia = createFont('georgia')
comic = createFont('comic sans ms')
arialBlack = createFont('arial black’)
courierNew = createFont('Courier New')
timesNewRoman = createFont("times new roman")

def drawText():
  fill(0)
  textFont(georgia, 30)
  text("Georgia", 200, 20)
  textFont(mono, 30)
  text("MonoSpace", 200, 70)
  textFont(verdana, 30)
  text("Verdana", 200, 120)
  textFont(comic, 30)
  text("Comic Sans", 200, 170)
  textFont(arialblack, 30)
  text("Arial black", 200, 220)
  textFont(CourierNew, 30)
  text("Courier New", 200, 270)
  textFont(timesNewRoman, 30)
  text("Times New Roman", 200, 320)
drawText()
